- alias: 'Dining Lights Notification'
  trigger:
    - platform: state
      entity_id: light.dining
      to: 'on'
    - platform: state
      entity_id: light.dining
      to: 'off'
  action:
    - service: tts.amazon_polly_say
#    - service: tts.google_say
      entity_id: media_player.mpd
      data_template:
        message: <speak>Turning the dining lights {{ states('light.dining') }}</speak>

- alias: 'TV Lights Notification'
  trigger:
    - platform: state
      entity_id: light.tv
      to: 'on'
    - platform: state
      entity_id: light.tv
      to: 'off'
  action:
    - service: tts.amazon_polly_say
#    - service: tts.google_say
      entity_id: media_player.mpd
      data_template:
        message: <speak>Turning the TV lights {{ states('light.tv') }}</speak>

- alias: 'Bedroom Lights Notification'
  trigger:
    - platform: state
      entity_id: light.bedroom
      to: 'on'
    - platform: state
      entity_id: light.bedroom
      to: 'off'
  action:
    - service: tts.amazon_polly_say
#    - service: tts.google_say
      entity_id: media_player.mpd
      data_template:
        message: <speak>Turning the bedroom lights {{ states('light.bedroom') }}</speak>

- alias: Startup Notification
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.ios_euge_iphone
      data:
        message: 'Home Asssitant has started'
    - service: tts.amazon_polly_say
      entity_id: media_player.mpd
      data_template:
        message: <speak>Hello Eugene. I am Ava. Home Assistant is up and running and all systems are good to go!</speak>

- alias: 'Leaving Home'
  trigger:
    platform: state
    entity_id: device_tracker.eugeiphone
    from: 'home'
    to: 'not_home'
  action:
    - service: notify.ios_euge_iphone
      data:
        message: 'See you'

- alias: 'Arriving Home'
  trigger:
    platform: state
    entity_id: device_tracker.eugeiphone
    from: 'Away'
    to: 'home'
  action:
    - service: notify.ios_euge_iphone
      data:
        message: 'Welcome home Eugene'

- alias: 'Leaving work'
  trigger:
    platform: state
    entity_id: device_tracker.eugeiphone
    from: 'Work'
    to: 'Away'
  action:
  - service: notify.ios_euge_iphone
    data:
      message: 'You have left work'

- alias: 'Coming to work'
  trigger:
    platform: state
    entity_id: device_tracker.eugeiphone
    from: 'Away'
    to: 'Work'
  action:
  - service: notify.ios_euge_iphone
    data:
      message: 'Get shit done today Eugene'
