- alias: 'Dining Lights Notification'
  trigger:
    - platform: state
      entity_id: light.dining_light
      to: 'on'
    - platform: state
      entity_id: light.dining_light
      to: 'off'
  action:
    - service: tts.amazon_polly_say
      entity_id: media_player.mpd
      data_template:
        message: <speak> <break time="1s"/>The dining light is {{ states('light.dining_light') }}</speak>

- alias: 'TV Lights Notification'
  trigger:
    - platform: state
      entity_id: light.tv_light
      to: 'on'
    - platform: state
      entity_id: light.tv_light
      to: 'off'
  action:
    - service: tts.amazon_polly_say
      entity_id: media_player.mpd
      data_template:
        message: <speak> <break time="1s"/>The TV light is {{ states('light.tv_light') }}</speak>

- alias: 'Bedroom Lights Notification'
  trigger:
    - platform: state
      entity_id: light.bedroom_light
      to: 'on'
    - platform: state
      entity_id: light.bedroom_light
      to: 'off'
  action:
    - service: tts.amazon_polly_say
      entity_id: media_player.mpd
      data_template:
        message: <speak><break time="1s"/> The bedroom light is {{ states('light.bedroom_light') }}</speak>

- alias: Startup Notification
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.ios_euge_iphone
      data:
        message: 'Home Asssitant has started'
    - service: tts.amazon_polly_say
      entity_id: media_player.mpd
      data_template:
        message: <speak>Hello Eugene. It's Alice. I am up and running and all systems are good to go!</speak>

- alias: Welcome home
  trigger:
    platform: state
    entity_id: device_tracker.eugeiphonenmap
    from: 'not_home'
    to: 'home'
  action:
  - service: notify.ios_euge_iphone
    data:
      message: Good morning. Welcome back home.
  - service: tts.amazon_polly_say
    entity_id: media_player.mpd
    data:
      message: <speak> Hello Eugene. Welcome back home.  </speak>

- alias: Welcome home Helen
  trigger:
    platform: state
    entity_id: device_tracker.heleniphone
    from: 'not_home'
    to: 'home'
  action:
  - service: notify.ios_euge_iphone
    data:
      message: Helen has come home
  - service: tts.amazon_polly_say
    entity_id: media_player.mpd
    data:
      message: <speak> Hello Helen! Welcome to my home!</speak>
