homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 50
  unit_system: metric
  time_zone: Asia/Hong_Kong
  customize: !include customize.yaml

http:
  api_password: !secret http_api_password
  base_url: eugenelai.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

updater:
####################### Components
discovery:
  ignore:
    - plex_mediaserver
    - apple_tv
config:
hassio:
wemo:
ios:
history:
logbook:
map:
sun:
frontend:

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: 'us-east-1'
    text_type: ssml
    voice: Joey

  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

emulated_hue:
  host_ip: 10.0.1.23

media_player:
  - platform: mpd
    host: 10.0.1.23

camera:
  - platform: generic
    still_image_url: http://10.0.1.107/ccm/ccm_pic_get.jpg?hfrom_handle=887330&dsess=1&dsess_nid=MBkLQ4J7oa.NKjadJjULRKNCIyRhLw&dsess_sn=1jfiegbp4eanq&dtoken=p0_xxxxxxxxxx

# Light setup
light:
  platform: limitlessled
  bridges:
    - host: 10.0.1.11
      version: 5
      port: 8899
      groups:
      - number: 1
        type: rgbw
        name: TV
      - number: 3
        type: rgbw
        name: Bedroom
      - number: 4
        type: rgbw
        name: Dining

# Device Tracker
device_tracker:
  - platform: icloud
    username: !secret apple_username
    password: !secret apple_password
    account_name: Euge iCloud

#  - platform: nmap_tracker
    #hosts: 10.0.1.1/24
#    scan_options: " --privileged -sn"
#    home_interval: 10
#    track_new_devices: yes

  - platform: bluetooth_tracker

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: https://eugenelai.duckdns.org:8321

# Weather Prediction
sensor:
  - platform: yr
  - platform: darksky
    api_key: !secret darksky_apikey
    monitored_conditions:
      - summary
      - temperature

  - platform: bitcoin
    currency: HKD
    display_options:
      - exchangerate


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
