homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 50
  unit_system: metric
  time_zone: Asia/Hong_Kong
  customize: !include customize.yaml

http:
  api_password: !secret http_api_password
  base_url: eugenelai.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ssl_profile: intermediate

  # api_password: !secret http_api_password
  # base_url: 192.168.86.94


discovery:
system_health:
updater:
cloud:
config:
hassio:
wemo:
ios:
history:
logbook:
map:
sun:
frontend:
  themes: !include themes.yaml
  javascript_version: latest
recorder:
  purge_keep_days: 5
weather:
  - platform: darksky
    api_key: !secret darksky_apikey

august:
  login_method: email
  username: !secret august_username
  password: !secret august_password
  timeout: 60


ifttt:
  key: !secret ifttt_key

alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_password
      url: amazon.com

# camera:
#   - platform: generic
#     still_image_url: !secret cameraaddress

# Light setup
light:
  - platform: limitlessled
    bridges:
      - host: 192.168.86.22
        version: 5
        port: 8899
        groups:
        - number: 1
          type: rgbw
          name: Living Room Light
          fade: true
        - number: 2
          type: rgbw
          name: Bedroom Light
          fade: true
        - number: 4
          type: rgbw
          name: Dining Light
          fade: true
  - platform: template
    lights:
      dresser_light:
        friendly_name: 'Dresser Light'
        turn_on:
          service: switch.turn_on
          entity_id: switch.bedroom_dresser
        turn_off:
          service: switch.turn_off
          entity_id: switch.bedroom_dresser
  - platform: flux_led
    devices:
      192.168.86.20:
        name: "Living Room Mood"
      192.168.86.21:
        name: "Bedroom Mood"

switch:
  - platform: template
    switches:
      bedroom_fan:
        friendly_name: "Bedroom Aircon"
        value_template: "{{ states('input_boolean.bedroomac') }}"
        turn_on:
          service: script.turn_on
          data:
            entity_id: script.bedroomacon
        turn_off:
          service: script.turn_on
          data:
            entity_id: script.bedroomacoff
  - platform: template
    switches:
      xboxmediaplayer:
        friendly_name: "Xbox"
        value_template: "{{ states('media_player.xbox') }}"
        turn_on:
          service: media_player.turn_on
        turn_off:
          service: media_player.turn_on
  - platform: broadlink
    host: 192.168.86.23
    mac: '78:0f:77:5a:dd:1d'
    timeout: 15
    switches:
      living_room_aircon:
        friendly_name: "Living Room Aircon"
        command_on: JgDKAI+PEzQTExI2EDcQFhAWEDcQFhAWEDcTExMTEzQTNBQTEzMTExMTExMTNBI1EjURNhA3EDcQNxA3EBYQFhAWEBYQFhAWEBYQNxA3EDcTExMTFBITNBQyFRITExMTEzQTNBM0EqWPjxMzFRITNBQzFBIUEhQzFBITExM0ExMTExM0ETcQFhA3EBYQFhAWEDcQNxA3EzUSNBM0EzQUMxQSExMQFhAWExQSExMUEzMUMxQzFBITExMTEzQTNBMTEhQSFRA2EDgPNxAADQUAAAAAAAAAAAAAAAAAAA==
        command_off: JgDKAI+PEzQTExQzFDQTExMTEzQSFREUEDcUEhMTEzQTMhUTEjUSFRA2EDcQNxA3EBYQNxM0EzQTExMTExMTExQzFBIUEhM0EzQTNBMTEhQSFBIUERYPFw8YDhYTNBM0EzQTNBQxFaSMkhA3EBYQNxA3EBYQFhM0ExMTExM0ExMUExI0EzQRFRA3EBYQNxA3EDcQNxAWEDYRNxA3ExMTExMTExMTNBMTFBITNBQzFDMUExITExMTExMTExMSFBIVEDYQNxA3EDcQOA8ADQUAAAAAAAAAAAAAAAAAAA==
      living_room_tv:
        friendly_name: "Living Room TV"
        command_on: JgBaAAiMAAEolw0YEBUSOA0YDxYRFRETEhMOPA87ERQOPA48DzoNPQ88EhMTEg0YETkQFQ0YERQSEw0+EDkQOg4XDzsMPQ48EjgQAAUuAAEmThEADGUAASVOEgANBQAAAAAAAAAAAAAAAAAA
        command_off: JgBYAAABKJcNGBEUEjgNGRETEhQSEhITDjwQOhEUDjwPOww9DzsQOg8XDxUPFhI4DRgPFw8WDhYPOxI4DT4NFxE5DD0QOhM3DQAFMQABJk4OAAxoAAEmTRIADQU=
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named script
zone: !include zones.yaml
sensor: !include sensors.yaml
device_tracker: !include devicetracker.yaml
intent_script: !include alexaintent.yaml
scene: !include scene.yaml

speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload

input_boolean:
  guest_mode:
    name: Guest Mode
    icon: mdi:home-modern

  silence_mode:
    name: Silence mode
    icon: mdi:volume-off

  bedroomac:
    name: Bedroom AC
    initial: off
  xbox:
    name: Xbox Status
    initial: off

#tts:
#  - platform: amazon_polly
#    aws_access_key_id: !secret aws_access_key_id
#    aws_secret_access_key: !secret aws_secret_access_key
#    region_name: 'us-east-1'
#    text_type: ssml
#    voice: Joanna

# panel_iframe:
#   pihole:
#     title: Pi-Hole
#     icon: mdi:block-helper
#     url: https://eugenelai.duckdns.org:4865

#emulated_hue:
#  host_ip: 10.0.1.23


# panel_iframe:
#   configurator:
#     title: Configurator
#     icon: mdi:wrench
#     url: http://eugenelai.duckdns.org:3218/
