homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 50
  unit_system: metric
  time_zone: Asia/Hong_Kong
  customize: !include customize.yaml

http:
  api_password: !secret http_api_password
  base_url: eugenelai.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

updater:
####################### Components
discovery:
  ignore:
    - plex_mediaserver
    - apple_tv
#cloud:
config:
hassio:
wemo:
ios:
history:
logbook:
map:
sun:
alexa:
frontend:
  themes: !include themes.yaml

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: 'us-east-1'
    text_type: ssml
    voice: Joanna

emulated_hue:
  host_ip: 10.0.1.23

media_player:
  - platform: mpd
    host: 10.0.1.23
camera:
  - platform: generic
    still_image_url: http://10.0.1.107/ccm/ccm_pic_get.jpg?hfrom_handle=887330&dsess=1&dsess_nid=MF4MbYVCGQHE90Me9yynvnlCB7VhAw&dsess_sn=1jfiegbp4eanq&dtoken=p0_xxxxxxxxxx
# Light setup
light:
  platform: limitlessled
  bridges:
    - host: 10.0.1.11
      version: 5
      port: 8899
      groups:
      - number: 1
        type: rgbw
        name: TV Light
        fade: true
      - number: 3
        type: rgbw
        name: Bedroom Light
        fade: true
      - number: 4
        type: rgbw
        name: Dining Light
        fade: true
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home assistant


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
sensor: !include sensors.yaml
device_tracker: !include devicetracker.yaml
intent_script: !include alexaintent.yaml
input_boolean: 
  running_reminder:
    name: Running Reminder
    icon: mdi:run
