homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 50
  unit_system: metric
  time_zone: Asia/Hong_Kong
  customize: !include customize.yaml

http:
  api_password: !secret http_api_password
  base_url: eugenelai.duckdns.org
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ssl_profile: intermediate

updater:
cloud:
config:
hassio:
wemo:
ios:
history:
logbook:
map:
sun:
frontend:
  themes: !include themes.yaml
  extra_html_url:
    - notificationhistory.txt
recorder:
  purge_keep_days: 5

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: 'us-east-1'
    text_type: ssml
    voice: Joanna

notify:
  - name: notifcationhistory
    platform: file
    filename: notificationhistory.txt

#emulated_hue:
#  host_ip: 10.0.1.23
august:
  login_method: email
  username: !secret august_username
  password: !secret august_password
  timeout: 60

media_player:
  - platform: mpd
    host: 10.0.1.23
  - platform: alexa
    email: !secret amazon_email
    password: !secret amazon_password
    url: "amazon.com"

camera:
  - platform: generic
    still_image_url: !secret cameraaddress

# Light setup
light:
  platform: limitlessled
  bridges:
    - host: 10.0.1.11
      version: 5
      port: 8899
      groups:
      - number: 1
        type: rgbw
        name: TV Light
        fade: true
      - number: 2
        type: rgbw
        name: Bedroom Light
        fade: true
      - number: 4
        type: rgbw
        name: Dining Light
        fade: true
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home assistant

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named script
zone: !include zones.yaml
sensor: !include sensors.yaml
device_tracker: !include devicetracker.yaml
intent_script: !include alexaintent.yaml
scene: !include scene.yaml

input_boolean:
#alarm
  alarmweekday:
    name: Weekdays Only
    icon: mdi:calendar
  alarmweekon:
    name: Alarm active

  guest_mode:
    name: Guest Mode
    icon: mdi:home-modern

  silence_mode:
    name: Silence mode
    icon: mdi:volume-off


#alarm
input_number:
  alarmhour:
    name: Hour
    icon: mdi:timer
    initial: 6
    min: 0
    max: 23
    step: 1
  alarmminutes:
    name: Minutes
    icon: mdi:timer
    initial: 30
    min: 0
    max: 59
    step: 5
