- platform: icloud
  username: !secret apple_username
  password: !secret apple_password
  account_name: Euge iCloud

- platform: nmap_tracker
  hosts: 10.0.1.1/24
  home_interval: 15 #NMAP option
  consider_home: 300
  interval_seconds: 900
  track_new_devices: no
  scan_options: " -sP --host-timeout 10s"
