- platform: icloud
  username: !secret apple_username
  password: !secret apple_password
  account_name: Euge iCloud

- platform: nmap_tracker
  hosts: 10.0.1.1/24
  home_interval: 30
  track_new_devices: no
  interval_seconds: 30
