- platform: icloud
  username: !secret apple_username
  password: !secret apple_password
  account_name: Euge iCloud

- platform: nmap_tracker
  hosts: 10.0.1.1/24
  consider_home: 300
  home_interval: 300
  interval_seconds: 120
  track_new_devices: no
