- platform: yr
- platform: darksky
  api_key: !secret darksky_apikey
  monitored_conditions:
    - summary
    - temperature
- platform: bitcoin
  currency: HKD
  display_options:
    - exchangerate
- platform: time_date
  display_options:
    - 'time'
    - 'date'
- platform: cert_expiry
  host: eugenelai.duckdns.org
- platform: version

# MQTT Sensors
- platform: mqtt
  state_topic: sensor/livingroom/temperature
  name: "Living Room Temperature"
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: sensor/livingroom/humidity
  name: "Living Room Humidity"
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: sensor/livingroom/motion
  name: "Living Room Motion"
- platform: mqtt
  state_topic: sensor/bedroom/temperature
  name: "Bedroom Temperature"
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: sensor/bedroom/humidity
  name: "Bedroom Humidity"
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: sensor/bedroom/motion
  name: "Bedroom Motion"

- platform: template
  sensors:
    euge_iphone:
      friendly_name: "Euge iPhone"
      value_template: >-
        {% if is_state('device_tracker.iphone', 'home') or is_state('device_tracker.eugeiphonenmap', 'home') or is_state('device_tracker.euge_iphone', 'home') %}
          Home
        {% else %}
          Away
        {% endif %}

#Bitcoin
- platform: bitcoin
  friendly_name: bitcoinhkd
  currency: HKD
  display_options:
    - exchangerate
#- platform: bitcoin
#  friendly_name: bitcoinusd
#  currency: USD
#  display_options:
#    - exchangerate

- platform: template
  sensors:
    bcvalue:
      friendly_name: "Bitcoin Wallet"
      value_template: " HKD{{ '{0:,.0f}'.format(states('sensor.exchange_rate_1_btc') | float * 0.113) | round(0) }}"

- platform: template
  sensors:
    bcratehkd:
      friendly_name: "Bitcoin HKD"
      value_template: "HKD{{ '{0:,.0f}'.format(states('sensor.exchange_rate_1_btc') | float ) | round(0) }}"

- platform: template
  sensors:
    bcrateusd:
      friendly_name: "Bitcoin USD"
      value_template: "USD{{ '{0:,.0f}'.format(states('sensor.exchange_rate_1_btc') | float / 7.8 ) | round(0) }}"

#- platform: template
#  sensors:
#    bcrateusd:
#      friendly_name: "Bitcoin USD"
#      value_template: "USD {{ '{0:,.0f}'.format((states.sensor.exchange_rate_1_btc.state) | float ) | round(0) }}"


- platform: systemmonitor
  resources:
    - type: memory_use_percent

# Google Transit code
#- platform: google_travel_time
#  api_key: !secret googleAPIKey
#  origin: zone.work
#  destination: zone.home
#  options:
#    mode: transit
