
############ Templated notifcations:

- alias: Templated Notification
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.eugene_location
    from: 'travelling'
    to: 'home'
  action:
    service: script.speech_notify_engine
    data_template:
      speech_message: >
        "{{trigger.entity_id}} is a test message using templates. Sent at: {{now().strftime('%Y-%m-%d %I:%M %p')}}"


- alias: Current Temperature
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.bedroom_temperature
    below: 25
  action:
    - service: script.speech_notify_engine
      data_template:
        speech_message: >
          "The current temperature of your bedroom has dropped to {{states.sensor.bedroom_temperature.state | round | int }}."
    - service: script.text_notify_engine
      data_template:
        text_message: >
          "The current temperature of your bedroom has dropped to {{states.sensor.bedroom_temperature.state | round | int }}."


- alias: 'Getting Up'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.eugenes_iphone_battery_state
    to: 'Charging'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.eugene_location
        state: 'home'
      - condition: time
        after: '05:00:00'
        before: '10:00:00'
  action:
    - service: light.turn_on
      entity_id: light.living_room_mood
    - service: script.speech_notify_engine
      data_template:
        speech_message: >
          {{ [
          "Good morning. The sun's coming up shortly. It's currently" + states.sensor.time.state+ ", and the temperature is" +  states.sensor.dark_sky_temperature.state  + " celcius. And is expected to be" +  states.sensor.dark_sky_summary.state ,
          "Rise and shine. It's " + states.sensor.time.state+ ". Today it is expected to be" +  states.sensor.dark_sky_summary.state  + ", and the temperature is" +  states.sensor.dark_sky_temperature.state + " celcius.",
          "Wake up now. It is" + states.sensor.time.state + ". The weather today is going to be" + states.sensor.dark_sky_summary.state + ", and the temperature is" +  states.sensor.dark_sky_temperature.state + " celcius."
          ] | random }}"
