
############ Templated notifcations:

- alias: Templated Notification
  trigger:
    platform: state
    entity_id: sensor.eugene_location
    from: 'travelling'
    to: 'home'
  action:
    service: script.speech_notify_engine
    data_template:
      speech_message: >
        "{{trigger.entity_id}} is a test message using templates. Sent at: {{now().strftime('%Y-%m-%d %I:%M %p')}}"


- alias: Current Temperature
  trigger:
    platform: numeric_state
    entity_id: sensor.bedroom_temperature
    below: 25
  action:
    - service: script.speech_notify_engine
      data_template:
        speech_message: >
          "The current temperature of your bedroom has dropped to {{states.sensor.bedroom_temperature.state | round | int }}."
    - service: script.text_notify_engine
      data_template:
        text_message: >
          "The current temperature of your bedroom has dropped to {{states.sensor.bedroom_temperature.state | round | int }}."
