- alias: 'Disconnect WiFi'
  trigger:
    - platform: state
      entity_id:
        - device_tracker.eugenesiphonenmap
        - device_tracker.heleniphone
      to: 'not_home'
  action:
    - service: script.text_notify_engine
      data_template:
        text_message: >
          {% if trigger.entity_id == "device_tracker.eugenesiphonenmap"%}
            {% set person = "Eugene"%}
          {% else %}
            {% set person = "Helen" %}
          {% endif %}
          {%- macro greeting_sentence(person) -%}
          {{ person + " has disconnected from WiFi"}}
          {%- endmacro -%}
          {{greeting_sentence(person)}}


- alias: 'People Greeting'
  trigger:
    - platform: state
      entity_id:
        - device_tracker.eugenesiphonenmap
        - device_tracker.heleniphone
      to: 'home'
  action:
    - service: script.speech_notify_engine
      data_template:
        speech_message: >
          {% if trigger.entity_id == "device_tracker.eugenesiphonenmap"%}
            {% set person = "Eugene"%}
          {% else %}
            {% set person = "Helen" %}
          {% endif %}
          {%- macro speech_greeting(person) -%}
          {{ [
          "Welcome back home " ~ person,
          "Guess who is home?" ~ person +" is!",
          person + " is now in the house.",
          "Welcome Home " ~ person + ".  We have missed you. Or at least Molly did.",
          "Our home is now complete, Rest your head and relax your feet! Welcome Back " ~ person,
          "Life is like a song, you’re back where you belong. Welcome home " ~ person,
          "Hey there " ~ person + " Welcome Home!",
          "Knock Knock. Who is There? "   ~ person +" is!",
          person ~ "! You are home!",
          "I know a secret! "  ~ person +" is home!",
          "I am sensing a disturbance in the force. "  ~ person +" must be home!",
          "And the house becomes a home. Welcome back " ~ person,
          person + " is now here.  Hash tag Welcome Home.",
          person + " is now here.  Hash tag Home.",
          "Just a quick announcement. " ~ person +" has arrived!",
          "Pardon the interruption but " ~ person +" is home!",
          "My systems are picking up the presence of additional humans. " ~ person +" has been identified as home."
          ] | random }}
          {%- endmacro -%}
          {{speech_greeting(person)}}
    - service: script.text_notify_engine
      data_template:
        text_message: >
          {% if trigger.entity_id == "device_tracker.eugenesiphonenmap"%}
            {% set person = "Eugene"%}
          {% else %}
            {% set person = "Helen" %}
          {% endif %}
          {%- macro text_greeting(person) -%}
          {{ person + " has come home."}}
          {%- endmacro -%}
          {{text_greeting(person)}}

- alias: Leaving work
  trigger:
    platform: state
    entity_id: sensor.eugene_location
    from: 'work'
    to: 'travelling'
  action:
    - service: script.text_notify_engine
      data_template:
        text_message: "Hope you smashed work today."

- alias: Leaving home
  trigger:
    platform: state
    entity_id: sensor.eugene_location
    from: 'home'
    to: 'travelling'
  action:
    - service: script.text_notify_engine
      data_template:
        text_message: "Safe journey"

- alias: 'Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: script.text_notify_engine
      data_template:
        text_message: "Update for Home Assistant is available."

- alias: Startup Notification
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: script.text_notify_engine
      data_template:
        text_message: "All systems up and running again."
    - service: script.speech_notify_engine
      data_template:
        speech_message: "Hello Eugene. It's Alice. I am up and running and all systems are good to go!"


- alias: Daily reminder
  trigger:
    - platform: time
      at: '7:00:00'
    - platform: time
      at: '20:00:00'
  action:
  - service: script.text_notify_engine
    data_template:
      text_message: |
        {% if now().strftime("%H")|int < 12 %}
        Good morning, Eugene.
        {% elif now().strftime("%H")|int < 18 %}
        Good afternoon, Eugene.
        {% else %}
        Good evening, Eugene.
        {% endif %}
        Don't forget to do take your 10 minutes to clear your head.
        {% if is_state("input_boolean.running_reminder", "0.0") %}
        I have noticed you haven't gone for your run yet this week. Don't forget to go!
        {% else %}
        You've successfully gone for your run this week! Keep it up!
        {% endif %}

- alias: Morning routine
  trigger:
    platform: sun
    event: sunrise
    offset: '-00:30:00'
  condition:
    condition: state
    entity_id: group.all_devices
    state: 'home'
  action:
  - service: script.speech_notify_engine
    data_template:
      speech_message: >
        {{ [
        "Good morning. The sun's coming up shortly",
        "Sorry to interrupt. I've taken the liberty to turn on the light for you. It'll be getting dark soon. "
        ] | random }}
  - service: light.turn_on
    entity_id: light.living_room_lamp

- alias: Evening lights
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  condition:
    condition: state
    entity_id: group.all_devices
    state: 'home'
  action:
  - service: script.speech_notify_engine
    data_template:
      speech_message: >
        {{ [
        "Pardon me. It appears it's going to be dark soon. Let me switch the light on for you.",
        "Sorry to interrupt. I've taken the liberty to turn on the light for you. It'll be getting dark soon. ",
        ] | random }}
  - service: light.turn_on
    entity_id: light.living_room_lamp
